language: erlang
otp_release:
  - 18.3
  - 17.5
  - R16B03

env:
  global:
    - PATH=./rebar3-3.1.1:$PATH

cache:
  directories:
    - ./rebar3-3.1.1
    - /home/travis/.cache/rebar3

before_script:
  - wget --no-check-certificate https://github.com/erlang/rebar3/archive/3.1.1.tar.gz
  - tar xvzf 3.1.1.tar.gz
  - cd rebar3-3.1.1
  - ./bootstrap
  - cd ..

script:
  - if [ "$TRAVIS_OTP_RELEASE" != "R16B03" -a
         "$TRAVIS_OTP_RELEASE" != "17.5" ]; then make dialyze; fi
  - make xref
  - make test
  - make brahmin_runner
