#+TITLE: Brahmin Runner
#+AUTHOR: Norbert Melzer

* Brahmin Runner

Ein kleines Tool welches ermöglicht die eigenen Teilnehmerprogramme für den [[https://pwb.asta-wedel.de/SS16-BrahminPacker/index.html][PWB
im Sommersemester 2016]] unter Wettbewerbsnahen Bedingungen zu testen.

** Vorraussetzungen

- Es wird eine [[http://www.erlang.org/][Erlang Umgebung]] benötigt, mindestens in Version =16B3= benötigt.
- Für das kompilieren wird ausserdem [[http://www.rebar3.org/][=rebar3=]] benötigt.[fn:1]

** Kompilieren

#+BEGIN_SRC shell
rebar3 escriptize # Es werden Abhängigkeiten heruntergeladen und kompiliert
cp _build/default/bin/brahmin_runner $euer_projekt_pfad
#+END_SRC

** Benutzen

Im Moment gibt es zwei Modi der Nutzung.

*** Wettbewerbsmodus

#+BEGIN_SRC shell
brahmin_runner <zeit> <problem>
#+END_SRC

Führt euer Programm unter Wettbewerbsähnlichen Bedingungen aus.

Dazu wird die Datei ~problems/<problem>.prb~ eingelesen und euer Programm durch
einen Aufruf von ~make run~ gestartet. Nach einem kurzen Countdown (5 Sekunden)
erhält euer Programm seine Daten über =stdin=.

Wärend der nun folgenden <zeit> Sekunden wird euch angezeigt wenn euer Programm
eine Lösung einreicht und eine Bewertung dieser Lösung im Vergleich zum
bisherigen Bestwert.

*** Validitätsprüfung

#+BEGIN_SRC shell
brahmin_runner validate <problem>
#+END_SRC

Überprüft ob ein gegebenes Problem (ebenfalls ~problems/<problem>.prb~) nach den
Regeln in einem gültigen Format vorliegt.

* Zusatzbemerkungen

Überprüfung eurer Lösung auf Gültigkeit und Berechnung der Punkte erfolgt mit
dem gleichen Code wie im Wettbewerb auch, ebenfalls der Parser wird der gleiche
sein. Sollte also eine Lösung von euch nicht angenommen werden, die eurer
Meinung nach korrekt wäre, dann bitte eine Meldung an mich. Allerdings werde ich
aus Fairness ab dem Monatswechsel am Parsing nur noch in Notfällen etwas ändern.

* Footnotes

[fn:1] Unter Umständen werdet ihr =rebar3= selbst kompilieren müssen, damit es
zu eurer Erlang Version passt.

# Local Variables:
# eval: (require 'ox-md)
# End:
